database:
  host: localhost

spring:
  profiles:
    active: default
  datasource:
    url: "jdbc:postgresql://${database.host}:5432/todo"
    platform: postgresql
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate.ddl-auto: create-drop
    open-in-view: true
  cache:
    cache-names: schemas