version: "3"
services:
  postgres:
    container_name: todo-db
    image: mdillon/postgis:9.6
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=todo
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
